sub_images = {
        "ocrd": "core",
        "ocrd-olena-binarize": "ocrd_olena",
        "ocrd-sbb-binarize": "sbb_binarization",
        "ocrd-sbb-textline-detector": "sbb_textline_detector",
        "ocrd-calamari-recognize": "ocrd_calamari",
        "ocrd-calamari-recognize03": "ocrd_calamari03",
        "ocrd-tesserocr-segment-region": "ocrd_tesserocr",
        "ocrd-tesserocr-segment-line": "ocrd_tesserocr",
        "ocrd-tesserocr-recognize": "ocrd_tesserocr",
        "ocrd-dinglehopper": "dinglehopper",
        "ocrd-cis-ocropy-clip": "ocrd_cis",
        "ocrd-cis-ocropy-resegment": "ocrd_cis",
        "ocrd-cis-ocropy-segment": "ocrd_cis",
        "ocrd-cis-ocropy-deskew": "ocrd_cis",
        "ocrd-cis-ocropy-denoise": "ocrd_cis",
        "ocrd-cis-ocropy-binarize": "ocrd_cis",
        "ocrd-cis-ocropy-dewarp": "ocrd_cis",
        "ocrd-cis-ocropy-recognize": "ocrd_cis",
        "ocrd-fileformat-transform": "ocrd_fileformat",
        "ocrd-segment-extract-pages": "ocrd_segment",
        "ocrd-segment-extract-regions": "ocrd_segment",
        "ocrd-segment-extract-lines": "ocrd_segment",
        "ocrd-segment-from-masks": "ocrd_segment",
        "ocrd-segment-from-coco": "ocrd_segment",
        "ocrd-segment-repair": "ocrd_segment",
        "ocrd-segment-evaluate": "ocrd_segment",
        "ocrd-preprocess-image": "ocrd_wrap",
        "ocrd-skimage-normalize": "ocrd_wrap",
        "ocrd-skimage-denoise-raw": "ocrd_wrap",
        "ocrd-skimage-binarize": "ocrd_wrap",
        "ocrd-skimage-denoise": "ocrd_wrap",
        "ocrd-eynollah-segment": "eynollah",
        "ocrd-anybaseocr-crop": "ocrd_anybaseocr",
        "ocrd-anybaseocr-deskew": "ocrd_anybaseocr",

        # non OCR-D CLI
        "ocr-transform": "ocrd_fileformat",
}
