#!/bin/bash
set -e

self=`realpath $0`
self_dir=`dirname "$self"`

DATA_SUBDIR=data
get_from_annex() {
  annex_get 'calamari-models/GT4HistOCR/2019-07-22T15_49+0200/*.ckpt*'
  annex_get 'tesseract-models/GT4HistOCR/*.traineddata'
  annex_get 'textline_detection/*.h5'
}
get_from_web() {
  download_to 'https://qurator-data.de/calamari-models/GT4HistOCR/model.tar.xz' 'calamari-models/GT4HistOCR/2019-07-22T15_49+0200'
  download_to 'https://qurator-data.de/tesseract-models/GT4HistOCR/models.tar'  'tesseract-models/GT4HistOCR'
  download_to 'https://qurator-data.de/sbb_textline_detector/models.tar.gz'     'textline_detection'
}
. $self_dir/qurator_data_lib.sh
handle_data


docker build --cache-from my_ocrd_workflow -t my_ocrd_workflow .
