#!/bin/sh
set -e

(
  cd data
  git annex init
  git annex upgrade
  for f in "calamari-models/GT4HistOCR/*.ckpt*" "tesseract-models/GT4HistOCR/*.traineddata" "textline_detection/*.h5"; do
    git annex get $f
    git annex fsck $f
  done
)

docker build -t my_ocrd_workflow .
