FROM my_ocrd_workflow-core

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG DINGLEHOPPER_COMMIT="6e47acd"


# Build pip installable stuff
RUN ${PIP_INSTALL} \
# Now the real stuff:
    https://github.com/qurator-spk/dinglehopper/archive/$DINGLEHOPPER_COMMIT.tar.gz


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-dinglehopper"]
