ARG GIT_COMMIT="latest"
FROM quratorspk/ocrd-galley-core:$GIT_COMMIT

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG OCRD_SEGMENT_VERSION="0.1.21"


# Build pip installable stuff
RUN ${PIP_INSTALL} \
# Now the real stuff:
        "ocrd-segment == ${OCRD_SEGMENT_VERSION}"


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-segment-extract-regions"]
