ARG GIT_COMMIT="latest"
FROM quratorspk/ocrd-galley-core:$GIT_COMMIT

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG OCRD_TROCR_COMMIT="250ff1c"


# Build pip installable stuff
RUN ${PIP_INSTALL} \
    https://github.com/qurator-spk/ocrd_trocr/archive/$OCRD_TROCR_COMMIT.tar.gz


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-trocr-recognize"]
