ARG GIT_COMMIT="latest"
FROM quratorspk/ocrd-galley-core-cuda10.0:$GIT_COMMIT

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG SBB_BINARIZATION_VERSION="0.0.10"


# Build pip installable stuff
RUN ${PIP_INSTALL} \
# Now the real stuff:
    "sbb_binarization == $SBB_BINARIZATION_VERSION"


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-sbb-binarize"]
