ARG GIT_COMMIT="latest"
FROM quratorspk/ocrd-galley-core-cuda10.0:$GIT_COMMIT

ARG PIP_INSTALL="pip install --no-cache-dir"


# Build pip installable stuff
RUN ${PIP_INSTALL} \
# Resolve conflicts early:
        'tensorflow-gpu == 1.15.*' \
        'calamari-ocr == 0.3.5' \
# Now the real stuff:
        'ocrd_calamari == 0.0.7'


# Check pip dependencies
RUN pip check


# Default command
RUN ln -s ocrd-calamari-recognize /usr/local/bin/ocrd-calamari-recognize03
CMD ["ocrd-calamari-recognize"]
