ARG DRONE_COMMIT="latest"
FROM quratorspk/ocrd-galley-core-cuda10.1:$DRONE_COMMIT


# XXX https://github.com/OCR-D/core/issues/642
#ARG PIP_INSTALL="pip install --no-cache-dir"
ARG PIP_INSTALL="pip install --no-cache-dir"
ARG OCRD_CALAMARI_VERSION="1.0.2"

# Build pip installable stuff
RUN ${PIP_INSTALL} \
        "ocrd_calamari == $OCRD_CALAMARI_VERSION"


# Copy OCR models
RUN mkdir -p /var/lib/calamari-models/GT4HistOCR
COPY data/calamari-models/GT4HistOCR/2019-12-11T11_10+0100 /var/lib/calamari-models/GT4HistOCR/2019-12-11T11_10+0100
# XXX experimental
#COPY data/calamari-models/GT4HistOCR/2019-12-18T17_24+0100-with-augmentation-UNTESTED /var/lib/calamari-models/GT4HistOCR/2019-12-18T17_24+0100
#COPY data/mirror/github.com/Calamari-OCR/calamari_models/gt4histocr                   /var/lib/calamari-models/GT4HistOCR-chreul


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-calamari-recognize"]
