ARG GIT_COMMIT="latest"
FROM quratorspk/ocrd-galley-core-cuda12.1:$GIT_COMMIT

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG SBB_TEXTLINE_DETECTOR_COMMIT="c4df3d6"


# Build pip installable stuff
RUN ${PIP_INSTALL} \
    # https://github.com/qurator-spk/sbb_textline_detection/issues/50
    "h5py < 3" \
    https://github.com/qurator-spk/sbb_textline_detector/archive/$SBB_TEXTLINE_DETECTOR_COMMIT.tar.gz


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-sbb-textline-detector"]
