ARG DRONE_COMMIT="latest"
FROM mikegerber/my_ocrd_workflow-core:$DRONE_COMMIT

ARG PIP_INSTALL="pip install --no-cache-dir"
# XXX ARG OCRD_FILEFORMAT_VERSION="0.2.0"


RUN apt-get update && \
    apt-get install -y \
      git \
      openjdk-11-jdk-headless \
      wget \
      unzip \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
# XXX pr
RUN git clone --depth 1 https://github.com/OCR-D/ocrd_fileformat.git && \
    cd ocrd_fileformat/ && \
    git fetch origin pull/28/head:pr-28 && \
    git checkout pr-28 && \
    git submodule update --init && \
    make install-fileformat install PREFIX=/usr/local && \
    cd .. && rm -rf ocrd_fileformat/


# Default command
CMD ['ocrd-fileformat-transform']
