ARG DRONE_COMMIT="latest"
FROM mikegerber/ocrd-galley-core:$DRONE_COMMIT

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG OCRD_SEGMENT_VERSION="0.1.8"


# Build pip installable stuff
RUN ${PIP_INSTALL} \
# Now the real stuff:
        "https://github.com/OCR-D/ocrd_segment/archive/v${OCRD_SEGMENT_VERSION}.tar.gz"


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-segment-extract-regions"]
