ARG GIT_COMMIT="latest"
FROM quratorspk/ocrd-galley-core-cuda12.1:$GIT_COMMIT

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG OCRD_ANYBASEOCR_VERSION="1.8.2"



# Build pip installable stuff
RUN ${PIP_INSTALL} \
    "ocrd_anybaseocr == ${OCRD_ANYBASEOCR_VERSION}"


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-anybaseocr-crop"]
