FROM my_ocrd_workflow-core

ARG PIP_INSTALL="pip3 install --no-cache-dir --use-feature=2020-resolver"
ARG OCRD_FILEFORMAT_VERSION="0.1.1"


RUN apt-get update && \
    apt-get install -y \
      openjdk-11-jdk-headless \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
RUN curl -sSL --retry 3 -O https://github.com/OCR-D/ocrd_fileformat/archive/v${OCRD_FILEFORMAT_VERSION}.tar.gz && \
    tar xvzf v${OCRD_FILEFORMAT_VERSION}.tar.gz && \
    cd ocrd_fileformat-${OCRD_FILEFORMAT_VERSION}/ && \
    make install-fileformat install PREFIX=/usr/local && \
    rm -rf v${OCRD_FILEFORMAT_VERSION}.tar.gz ocrd_fileformat-${OCRD_FILEFORMAT_VERSION}/


# Default command
CMD ['ocrd-fileformat-transform']
