FROM ubuntu:22.04

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG OCRD_VERSION_MINIMUM="2.23.3"
ENV LC_ALL=C.UTF-8 LANG=C.UTF-8
ENV PIP_DEFAULT_TIMEOUT=120


RUN echo "APT::Acquire::Retries \"3\";" > /etc/apt/apt.conf.d/80-retries && \
    apt-get update && \
    apt-get install -y \
      curl xz-utils \
      build-essential python3-dev \
# For get-pip.py:
      python3-distutils \
# For add-apt-repository:
      software-properties-common \
# XML utils
      libxml2-utils \
      xmlstarlet \
# OCR-D uses ImageMagick for pixel density estimation
      imagemagick \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Set up OCR-D logging
RUN echo "setOverrideLogLevel(os.getenv('LOG_LEVEL', 'INFO'))" >/etc/ocrd_logging.py


# Install pip (and setuptools)
# We use get-pip.py here to avoid
# a. having to upgrade from Ubuntu's pip
# b. the dreaded "old script wrapper" error message
RUN curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3 get-pip.py && \
    rm -f get-pip.py


# Install pip installable-stuff
RUN ${PIP_INSTALL} \
        "ocrd >= ${OCRD_VERSION_MINIMUM}"


# Check pip dependencies
RUN pip check


WORKDIR /data

# Default command
CMD ['ocrd']
