ARG DRONE_COMMIT="latest"
FROM mikegerber/my_ocrd_workflow-core-cuda10.0:$DRONE_COMMIT

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG SBB_BINARIZATION_COMMIT="ea69494"


# Build pip installable stuff
RUN ${PIP_INSTALL} \
# Now the real stuff:
    https://github.com/qurator-spk/sbb_binarization/archive/$SBB_BINARIZATION_COMMIT.tar.gz


# Copy models
COPY data/sbb_binarization /var/lib/sbb_binarization


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-sbb-binarize"]
