ARG DRONE_COMMIT="latest"
FROM quratorspk/ocrd-galley-core:$DRONE_COMMIT

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG OCRD_FILEFORMAT_VERSION="0.2.0"


RUN apt-get update && \
    apt-get install -y \
      git \
      openjdk-11-jdk-headless \
      wget \
      unzip \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 --branch v${OCRD_FILEFORMAT_VERSION} https://github.com/OCR-D/ocrd_fileformat.git && \
    cd ocrd_fileformat/ && \
    git submodule update --init && \
    make install-fileformat install PREFIX=/usr/local && \
    cd .. && rm -rf ocrd_fileformat/


# Default command
CMD ['ocrd-fileformat-transform']
