FROM my_ocrd_workflow-core


# XXX https://github.com/OCR-D/core/issues/642
#ARG PIP_INSTALL="pip install --no-cache-dir --use-feature=2020-resolver"
ARG PIP_INSTALL="pip install --no-cache-dir"
ARG OCRD_CALAMARI_VERSION="1.0.0"

# Build pip installable stuff
RUN ${PIP_INSTALL} \
        "ocrd_calamari == $OCRD_CALAMARI_VERSION"


# Copy OCR models
RUN mkdir -p /var/lib/calamari-models/GT4HistOCR
COPY data/calamari-models/GT4HistOCR/2019-12-11T11_10+0100 /var/lib/calamari-models/GT4HistOCR/2019-12-11T11_10+0100



# Check pip dependencies
# XXX https://github.com/OCR-D/core/issues/642
#RUN pip check


# Default command
CMD ["ocrd-calamari-recognize"]
