FROM my_ocrd_workflow-core

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG TESSDATA_BEST_VERSION="4.0.0"
ARG OCRD_TESSEROCR_VERSION="0.11.0"
ENV TESSDATA_PREFIX /usr/local/share/tessdata


# Install Leptonica and Tesseract.
RUN add-apt-repository ppa:alex-p/tesseract-ocr && \
    apt-get update && \
    apt-get install -y \
        tesseract-ocr \
        libtesseract-dev \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


# Copy OCR models
RUN mkdir -p $TESSDATA_PREFIX
ADD data/mirror/github.com/tesseract-ocr/tessdata_best/archive/${TESSDATA_BEST_VERSION}-repacked.tar.gz $TESSDATA_PREFIX/
COPY data/tesseract-models/GT4HistOCR/GT4HistOCR_2000000.traineddata $TESSDATA_PREFIX/
RUN curl -sSL -O https://ub-backup.bib.uni-mannheim.de/~stweil/ocrd-train/data/Fraktur_5000000/tessdata_fast/Fraktur_50000000.502_198857.traineddata && \
    mv *.traineddata $TESSDATA_PREFIX/

# Build pip installable stuff
RUN ${PIP_INSTALL} \
    "ocrd_tesserocr == ${OCRD_TESSEROCR_VERSION}"


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-tesserocr-recognize"]
