FROM my_ocrd_workflow-core


# XXX https://github.com/OCR-D/core/issues/642
#ARG PIP_INSTALL="pip3 install --no-cache-dir --use-feature=2020-resolver"
ARG PIP_INSTALL="pip3 install --no-cache-dir"


# Build pip installable stuff
RUN ${PIP_INSTALL} \
        https://github.com/OCR-D/ocrd_calamari/archive/feat/update-calamari1.zip


# Copy OCR models
RUN mkdir -p /var/lib/calamari-models/GT4HistOCR
COPY data/calamari-models/GT4HistOCR/2019-12-11T11_10+0100 /var/lib/calamari-models/GT4HistOCR/2019-12-11T11_10+0100



# Check pip dependencies
# XXX https://github.com/OCR-D/core/issues/642
#RUN pip3 check


# Default command
RUN ln -s ocrd-calamari-recognize /usr/local/bin/ocrd-calamari-recognize-feat-update-calamari1
CMD ["ocrd-calamari-recognize"]
