ARG GIT_COMMIT="latest"
FROM quratorspk/ocrd-galley-core:$GIT_COMMIT

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG OCRD_WRAP_VERSION="0.1.7"


# Build pip installable stuff
RUN ${PIP_INSTALL} \
    "ocrd_wrap == ${OCRD_WRAP_VERSION}"


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-preprocess-image"]
