ARG DRONE_COMMIT="latest"
FROM quratorspk/ocrd-galley-core:$DRONE_COMMIT

ARG PIP_INSTALL="pip install --no-cache-dir"
ARG DINGLEHOPPER_COMMIT="d726396"


# Build pip installable stuff
RUN ${PIP_INSTALL} \
# Now the real stuff:
    https://github.com/qurator-spk/dinglehopper/archive/$DINGLEHOPPER_COMMIT.tar.gz


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-dinglehopper"]
