#!/bin/sh
# XXX Do not run privileged, use udica instead
docker run --user `id -u`:`id -g` --gpus all --rm -t --mount type=bind,src="$(pwd)",target=/data --privileged=true -e LOG_LEVEL=$LOG_LEVEL my_ocrd_workflow
