#!/bin/sh
# Run the my_ocrd_workflow container on the current workspace

# The container currently needs to run privileged to allow it to read from e.g.
# /home on SELinux secured systems such as Fedora. We might want to use udica
# instead in the future.

DOCKER_IMAGE=mikegerber/my_ocrd_workflow:stable `dirname $0`/run
